# **Exemplos com lista Numpy**


In [ ]:
lista = [1,2,3]

In [ ]:
np.array(lista)

array([1, 2, 3])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
arr = np.zeros((5,5))

In [ ]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones((5,5))

In [ ]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [ ]:
np.random.rand(5)

array([0.85503875, 0.10039671, 0.56981021, 0.80358933, 0.95617632])

In [ ]:
np.random.rand(5, 3)

array([[0.03142385, 0.45599234, 0.57517429],
       [0.60783661, 0.83078805, 0.56308155],
       [0.99929615, 0.76224162, 0.35718252],
       [0.5623375 , 0.47064933, 0.79257641],
       [0.49516362, 0.51556838, 0.88950437]])

In [ ]:
np.random.randn(4)

array([-0.41376637,  0.21902785, -1.26499614,  2.70079731])

In [ ]:
np.random.randint(0, 50, 2)

array([31, 24])

In [ ]:
arr = np.random.rand(25)

In [ ]:
arr

array([0.60232804, 0.19097111, 0.61160186, 0.33045255, 0.27610434,
       0.62637719, 0.51280619, 0.15505511, 0.43555063, 0.15382119,
       0.22041939, 0.92260971, 0.36194363, 0.89358631, 0.55619   ,
       0.32707515, 0.4252791 , 0.5740884 , 0.85548461, 0.08389984,
       0.35097002, 0.26646006, 0.03110901, 0.81047887, 0.6796656 ])

In [ ]:
arr.reshape(5,5)

array([[0.60232804, 0.19097111, 0.61160186, 0.33045255, 0.27610434],
       [0.62637719, 0.51280619, 0.15505511, 0.43555063, 0.15382119],
       [0.22041939, 0.92260971, 0.36194363, 0.89358631, 0.55619   ],
       [0.32707515, 0.4252791 , 0.5740884 , 0.85548461, 0.08389984],
       [0.35097002, 0.26646006, 0.03110901, 0.81047887, 0.6796656 ]])

In [ ]:
arr

array([0.60232804, 0.19097111, 0.61160186, 0.33045255, 0.27610434,
       0.62637719, 0.51280619, 0.15505511, 0.43555063, 0.15382119,
       0.22041939, 0.92260971, 0.36194363, 0.89358631, 0.55619   ,
       0.32707515, 0.4252791 , 0.5740884 , 0.85548461, 0.08389984,
       0.35097002, 0.26646006, 0.03110901, 0.81047887, 0.6796656 ])

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

**Operações com Numpy Array** 

In [ ]:
arr.shape

(5, 10)

In [ ]:
arr.max()

100

In [ ]:
arr.min()

0.031109007493705043

In [ ]:
arr.argmax()

11

In [ ]:
arr.argmin()

22

In [ ]:
arr.max

<function ndarray.max>

In [ ]:
arr.max

<function ndarray.max>

In [ ]:
arr = np.arange(0, 30, 3)

In [ ]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
arr[3]

9

In [ ]:
arr[2:5]

array([ 6,  9, 12])

In [ ]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [ ]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
arr = np.arange(50).reshape((5,10))

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr.shape

(5, 10)

In [ ]:
arr2 = arr[:3]

In [ ]:
arr2[:] = 100

In [ ]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [ ]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [ ]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [ ]:
arr > 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
bol = arr > 50

In [ ]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [ ]:
array = np.linspace(0, 100,30)

In [ ]:
array.shape

(30,)

In [ ]:
array = array.reshape(3,10)

In [ ]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [ ]:
array[0:2,2]

array([ 6.89655172, 41.37931034])

In [ ]:
np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr + arr

array([[200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98]])

In [ ]:
test = np.arange(0,16)

In [ ]:
test + test

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
arr - arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
test - test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
test * test

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [ ]:
test ** test

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
        1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
        1500973039], dtype=int32)

In [ ]:
test + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
np.sqrt(test)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [ ]:
np.exp(test)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [ ]:
np.mean(test)

7.5

In [ ]:
np.std(test)

4.6097722286464435

In [ ]:
np.sin(test)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [ ]:
np.max(test)

15

In [ ]:
np.min(test)

0